CREATE DATABASE IF NOT EXISTS buscai_db;
USE buscai_db;

CREATE TABLE IF NOT EXISTS mercado (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    localizacao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS produto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    disponivel BOOLEAN DEFAULT TRUE,
    mercado_id INT,
    FOREIGN KEY (mercado_id) REFERENCES mercado(id) ON DELETE CASCADE
);
