package backend.models;

public enum Categoria {
    HIGIENE_PESSOAL,
    ALIMENTOS_NAO_PERECIVEIS,
    ALIMENTOS_CONGELADOS,
    ALIMENTOS_PERECIVEIS,
    BEBIDAS,
    HORTIFRUTI_E_CARNES,
    PRODUTOS_DE_LIMPEZA,
    PRODUTOS_PARA_PETS;
}
